<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Threec-dev] Trouble running threec
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/threec-dev/2005-October/index.html" >
   <LINK REL="made" HREF="mailto:threec-dev%40lists.berlios.de?Subject=Re%3A%20%5BThreec-dev%5D%20Trouble%20running%20threec&In-Reply-To=%3Ca5d9c4580510221728p223434b4raebc80d23953b918%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000001.html">
   <LINK REL="Next"  HREF="000003.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Threec-dev] Trouble running threec</H1>
    <B>Rob Renaud</B> 
    <A HREF="mailto:threec-dev%40lists.berlios.de?Subject=Re%3A%20%5BThreec-dev%5D%20Trouble%20running%20threec&In-Reply-To=%3Ca5d9c4580510221728p223434b4raebc80d23953b918%40mail.gmail.com%3E"
       TITLE="[Threec-dev] Trouble running threec">rrenaud at gmail.com
       </A><BR>
    <I>Sun Oct 23 02:28:20 CEST 2005</I>
    <P><UL>
        <LI>Previous message: <A HREF="000001.html">[Threec-dev] Interesting links related to linux sandboxes
</A></li>
        <LI>Next message: <A HREF="000003.html">[Threec-dev] An experiment that has to do with our project
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2">[ date ]</a>
              <a href="thread.html#2">[ thread ]</a>
              <a href="subject.html#2">[ subject ]</a>
              <a href="author.html#2">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>I installed TurboGears with ez_setup.py, and then I run the server with

rob:~/code/trunk/threec$ python threec-start.py

And it seems to start up fine, but then when I visit localhost:8080, I
get the following error message,

500 Internal error

Server got itself in trouble

Traceback (most recent call last):
  File &quot;/usr/lib/python2.4/site-packages/CherryPy-2.1.0_rc2-py2.4.egg/cherrypy/_cphttptools.py&quot;,
line 271, in run
    main()
  File &quot;/usr/lib/python2.4/site-packages/CherryPy-2.1.0_rc2-py2.4.egg/cherrypy/_cphttptools.py&quot;,
line 502, in main
    body = page_handler(*args, **cherrypy.request.paramMap)
  File &quot;/usr/lib/python2.4/site-packages/TurboGears-0.8a3-py2.4.egg/turbogears/controllers.py&quot;,
line 122, in newfunc
    return controllers._process_output(tg_format, output, html)
  File &quot;/usr/lib/python2.4/site-packages/TurboGears-0.8a3-py2.4.egg/turbogears/controllers.py&quot;,
line 38, in _process_output
    output = view.render(output, tg_format, template=template)
  File &quot;/usr/lib/python2.4/site-packages/TurboGears-0.8a3-py2.4.egg/turbogears/view.py&quot;,
line 99, in render
    return t.serialize(encoding=&quot;utf-8&quot;, output=format, fragment=fragment)
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/__init__.py&quot;,
line 231, in serialize
    return serializer.serialize(self, encoding, fragment)
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/serialization.py&quot;,
line 47, in serialize
    text = list(self.generate(stream, encoding, fragment))
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/serialization.py&quot;,
line 301, in generate
    for ev, item in self.apply_filters(stream):
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/serialization.py&quot;,
line 73, in balancing_filter
    for ev, item in stream:
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/pull.py&quot;,
line 179, in _coalesce
    for ev, item in stream:
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/filter.py&quot;,
line 21, in transform_filter
    for ev, item in apply_matches(stream, template, templates, apply_func):
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/filter.py&quot;,
line 31, in apply_matches
    item = stream.expand()
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/pull.py&quot;,
line 87, in expand
    for ev, item in self._iter:
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/pull.py&quot;,
line 152, in _track
    for p in stream:
  File &quot;/usr/lib/python2.4/site-packages/kid-0.7adev_r186-py2.4.egg/kid/pull.py&quot;,
line 179, in _coalesce
    for ev, item in stream:
  File &quot;/home/rob/code/trunk/threec/threec/templates/homepage.py&quot;,
line 79, in _pull
NameError: name 'has_key' is not defined

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000001.html">[Threec-dev] Interesting links related to linux sandboxes
</A></li>
	<LI>Next message: <A HREF="000003.html">[Threec-dev] An experiment that has to do with our project
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#2">[ date ]</a>
              <a href="thread.html#2">[ thread ]</a>
              <a href="subject.html#2">[ subject ]</a>
              <a href="author.html#2">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/threec-dev">More information about the Threec-dev
mailing list</a><br>
</body></html>
